### ISSUE TITLE
Option to use parinfer-rust

### ISSUE THREAD

**Issue by GrayJack** [oakmac/atom-parinfer#105]
The project [parinfer-rust](https://github.com/eraserhd/parinfer-rust) are in active development, different of the JS version, that are archived.

**Comment by oakmac** [comment]
> the JS version, that are archived

Just because the original repo is archived doesn't mean anything is wrong with the code :wink: But I take your point: it would be nice to have a dependency chain that has an active maintainer. I have been thinking of taking on this project myself, but have not made it a priority so far.

I am familiar with parinfer-rust and know @eraserhd from Clojure/conj :smile: I'm sure it is possible to write a node.js bridge to parinfer-rust and use that for this extension, but I'm not sure if it would really effect end users too much. parinfer.js is pretty fast. The complexity / difficulty with this extension is getting the editor integration correct (this is true for all parinfer / editor integrations).

**Comment by GrayJack** [comment]
Yeah, I have no problems with parinfer JS speed, I do have a bit of a problem when comes to lisp-like that don't follow `;` for comment, making it not work so well with comments. As example Janet, it does it wrong when it comes to comment and when it comes to their `splice` shorthand (that is `;`)

 parinfer-rust fix that, since it can configure what the comment symbol are

**Comment by oakmac** [comment]
Yup :) https://github.com/shaunlebron/parinfer/issues/195

**Comment by oakmac** [comment]
Fixing that issue may be the driving factor in me forking parinfer.js and being an active maintainer :laughing:

**Comment by GrayJack** [comment]
Yeah, I wanted to do the same, but that would require me to learn JS properly first :laughing: 
I just known the minimal to create a tree-sitter grammar, that just require to learn how to use tree-sitter functions and follow other people examples :laughing:

**Comment by oakmac** [comment]
I created an up-to-date fork of parinfer.js at [github.com/oakmac/parinfer](https://github.com/oakmac/parinfer) and published [version 3.13.0](https://www.npmjs.com/package/@chrisoakman/parinfer) with support for comment characters other than `;`

v1.24.0 of atom-parinfer uses this new parinfer.js version with defaults for Janet so that it should "just work" without any additional configuration / modifications (see PR #106 and PR #107).

On the parinfer-rust front, looks like there might be some activity happening at [github.com/mauricioszabo/atom-parinfer-plus](https://github.com/mauricioszabo/atom-parinfer-plus)
