### ISSUE TITLE
Parinfer’s changes to the text should be put on the Undo stack

### ISSUE THREAD

**Issue by roryokane** [oakmac/atom-parinfer#27]
Parinfer’s changes are currently not undoable. This isn’t just a missing feature, it also corrupts the undo history.

To reproduce:

1.  Open a new file.
1.  Type `(`. If a `)` is automatically inserted, delete it.
1.  Turn on Parinfer. This will change the text to `()`.
1.  Type `def foo`. Now the text will be `(def foo)`.
1.  Turn off Parinfer.
1.  Hit Undo a few times until there is nothing more to undo.

The text will now be `)`, but it should be empty. Every change made to the text should have undone.

This messed me up when I used Parinfer-indent on [some wrongly-indented code](https://en.wikibooks.org/w/index.php?title=Clojure_Programming/Examples/Norvig_Spelling_Corrector&oldid=2690984), and I couldn’t undo the bad inferring of parentheses.

**Comment by oakmac** [comment]
This is a tricky issue. I [intentionally removed] Parinfer's changes from the undo history because it makes "undo" unusable otherwise.

Example:

1. Type some Lisp.
1. Parinfer infers parens and changes your code.
1. Apply "undo" to remove Parinfer's changes.
1. Atom sees that the code has changed and runs Parinfer, which changes the text back to exactly the code you just undid.

When using Parinfer in Indent Mode (which is the primary use case of Parinfer), most closing parens are the result of a pure function. The user is giving up control of editing the closing parens in favor of Parinfer's algorithm that writes them based on indentation.

Did Paren Mode run on the "wrongly-indented code" first before dropping you into Indent Mode? That [feature exists] to mitigate the problem you outlined.

[intentionally removed]:https://github.com/oakmac/atom-parinfer/blob/f738fa256a3eab6fc4c9b68b3447f292640d2e3e/src-cljs/atom_parinfer/core.cljs#L248-L250
[feature exists]:https://shaunlebron.github.io/parinfer/#fixing-existing-files

**Comment by roryokane** [comment]
No, Paren Mode didn’t run on the wrongly-indented code. That would have fixed my problem.

I see now that the plugin runs Paren Mode like it should when you open a new file with Indent Mode activated. Paren Mode didn’t run because I was opening the differently-formatted file in a different way, by copying and pasting it into an unsaved file.

How about you make the plugin run Paren Mode on pasted code too? Not typed text, just pasted text. If the pasted text came from an outside source, it will be sanitized so Indent Mode won’t change its behavior. And if the text came from some buffer using Indent Mode, then the round-trip won’t change the code at all.

For testing, here is portion of [the code](https://en.wikibooks.org/w/index.php?title=Clojure_Programming/Examples/Norvig_Spelling_Corrector&oldid=2690984) that Paren Mode should have run on:

```clojure
(defn edits1 [word]
  (let [alphabet "abcdefghijklmnopqrstuvwxyz", n (count word)]
    (distinct (concat
      (for [i (range n)] (str (subs word 0 i) (subs word (inc i))))
      (for [i (range (dec n))]
        (str (subs word 0 i) (nth word (inc i)) (nth word i) (subs word (+ 2 i))))
      (for [i (range n) c alphabet] (str (subs word 0 i) c (subs word (inc i))))
      (for [i (range (inc n)) c alphabet] (str (subs word 0 i) c (subs word i)))))))

(defn known [words nwords] (let [result (set (for [w words :when (nwords w)]  w))]
                             (if (empty? result)
                             nil
                             result)))
```

As for my example where `)` is still left after undoing everything, I think the confusing thing about the behavior is that Parinfer is turned off at the point when I run Undo. So ideally, Parinfer should have let go of responsibility for the ending brackets, and given that responsibility back to the Undo system. But from the undo-disabling code you linked, I understand that Atom’s undo model might make that too hard to implement. At least now I know that Undo will work correctly so long as I leave Parinfer on during the undoing.
