### ISSUE TITLE
previewCursorScope default on or default off?

### ISSUE THREAD

**Issue by oakmac** [oakmac/atom-parinfer#68]
Using this issue to track whether `previewCursorScope` should be "default on" or "default off".

As of v1.16.0, `previewCursorScope` is "default off", but can be enabled via [config file](https://github.com/oakmac/atom-parinfer/issues/67#issuecomment-239713095).

@shaunlebron and I agree that the default setting will be what the majority of people use, and thus it is an important decision in terms of Parinfer usability. As of August 2016, the [atom-parinfer package](https://atom.io/packages/parinfer) is approaching 10k downloads; it is likely the most popular real-world usage of Parinfer at this time.

If you are reading this issue, please enable `previewCursorScope` for some time (a week or two) and post here with your thoughts / impressions. We specifically ask that you spend more than just a day or two with it enabled (a week should be good), as we want to avoid opinions that are simply "it's not what I'm familiar with!". Give it a go, get used to it, then turn it off and see if you miss it. Then post here :)

---

What is `previewCursorScope`? From the [parinfer.js API](https://github.com/shaunlebron/parinfer/tree/master/lib#api):

`previewCursorScope` - when set to true in Indent Mode, it shows the cursor's scope on an empty line by inserting close-parens after it. For example:

With `previewCursorScope = false`:

``` clj
(let [foo 1
     bar 2]
     |
 (+ foo bar))
```

And with `previewCursorScope = true`:

``` clj
(let [foo 1
     bar 2
     |]
 (+ foo bar))
```

**Comment by oakmac** [comment]
Calling all atom-parinfer users!

cc: @victor-acuna @comamitc @pgambling @martinklepsch @roryokane @imalooney

**Comment by shaunlebron** [comment]
After a week of using it, my feeling is to leave it off by default and to place it in the settings screen for enabling.  It can feel _slightly_ intrusive or unexpected at times, and can be left dangling when clicking around or saving a file.  And it feels like an "extra thing" type of feature.

But turning it off by default is not a de-facto axing of the feature.  There's plenty of precedent for letting curious users find helpful extra features when they're ready.  Google and Apple come to mind since there are plenty of great _off-by-default_ features like pressing 'c' to compose an email, or holding ⌥ inside a menu to see more options.

**Comment by comamitc** [comment]
I haven't gotten to use it extensively, but one my OSS stuff I kept this on for > 1 week. I'd just echo that at times it felt a bit clunky when turned on. I can see where it's application is helpful but I'd, by default, keep it off.

**Comment by oakmac** [comment]
I had this setting turned on for about 2 weeks. I think it's best left default off. It got in my way more than it helped.
